version: 0.2
phases:
  install:
    commands:
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.16.12/2020-07-08/bin/linux/amd64/ku bectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl
      - mkdir ~/.kube
      - aws eks --region ap-northeast-2 update-kubeconfig --name <YOUR-CLUSTER-NAME>
      - kubectl get nodes
  pre_build:
    commands:
      - echo Pre Build started on `date`
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - kubectl apply -f ./bookinfo.yaml

